### PR TITLE
Fixed python sqlparse module importing issue.

### PR DESCRIPTION
**Pull request by ronxin**
This file seems to be interfering with the loading of sqlparse. Without this file, installation and running of modified sqlparse works fine by following the instructions in README.

### CODE REVIEW

**Comment by sriniiyer** [comment]
Hmm, somehow that doesn't sound right. That file is needed for that folder to be searched by python for modules. Are you sure you set the PYTHONPATH correctly? Are you sure its using the modified sqlparse and not the stock version?

**Comment by ronxin** [comment]
I have tested on different machines. It seems that different python installations can have different search orders for packages.

After configuring `PYTHONPATH` and installing the modified `sqlparse`, open up a python interpreter (better, ipython), and type `import sys; sys.path`. You will see paths that look like below (might be in different order):

[1] `/usr/local/lib/python2.7/dist-packages/sqlparse`
[2] `/home/username/codenn/src`
[3] `/home/username/codenn/src/sqlparse`

Path [1] is the result of installation, and paths [2] & [3] are the result of specifying `PYTHONPATH`. If [1] appears before [2] and [3], then it is fine. If, however, [1] appears after [2] and [3], which does happen on one of my machines,  then python first tries to find `sqlparse` module in [2], and it can indeed find `sqlparse` in `~/src`, but it is not going to load anything because of the empty `__init__.py` file. So one would see error like this when running `buildData.py`:

```
Traceback (most recent call last):
  File "buildData.py", line 128, in <module>
    vocab = buildVocab(os.environ['CODENN_DIR'] + '/data/stackoverflow/' + lang + '/train.txt', code_unk_threshold, nl_unk_threshold, lang)
  File "buildData.py", line 47, in buildVocab
    tokens.update(tokenizeCode(code, lang))
  File "buildData.py", line 23, in tokenizeCode
    query = SqlTemplate(code, regex=True)
  File "/home/username/codenn/src/sql/SqlTemplate.py", line 80, in __init__
    self.parse = sqlparse.parse(self.sql)
AttributeError: 'module' object has no attribute 'parse'
```

That's why I suggest removing `__init__.py`. It does not do anything anyway. And the error it causes can only be exposed on certain python installations.

I probably have spent way too much time on this issue:-) But I really wanted to reproduce it on my machine and have everyone else do so without problem either. I appreciated you open-sourcing the code and data. Everyone should be doing this.

**Comment by greenberet** [comment]
Sounds good. Thanks!

**Comment by sriniiyer** [comment]
Sounds good. Thanks!

**Pull request merged**
